let a={
  id: 'sub_1OHPb8DnX1DMWAG3OJLJWyRW',
  object: 'subscription',
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1701171422,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: { comment: null, feedback: null, reason: null },
  collection_method: 'charge_automatically',
  created: 1701171422,
  currency: 'usd',
  current_period_end: 1703763422,
  current_period_start: 1701171422,
  customer: 'cus_P5amQ9ggLORF9V',
  days_until_due: null,
  default_payment_method: 'card_1OHPb6DnX1DMWAG3YGiuHitE',
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: {
    id: 'di_1OHPb8DnX1DMWAG3hjv1Ult7',
    object: 'discount',
    checkout_session: null,
    coupon: {
      id: 'b37hKTYg',
      object: 'coupon',
      amount_off: 500,
      created: 1701078802,
      currency: 'usd',
      duration: 'forever',
      duration_in_months: null,
      livemode: false,
      max_redemptions: null,
      metadata: {},
      name: 'HAPPY',
      percent_off: null,
      redeem_by: null,
      times_redeemed: 1,
      valid: true
    },
    customer: 'cus_P5amQ9ggLORF9V',
    end: null,
    invoice: null,
    invoice_item: null,
    promotion_code: null,
    start: 1701171422,
    subscription: 'sub_1OHPb8DnX1DMWAG3OJLJWyRW'
  },
  ended_at: null,
  items: {
    object: 'list',
    data: [ [Object] ],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1OHPb8DnX1DMWAG3OJLJWyRW'
  },
  latest_invoice: {
    id: 'in_1OHPb8DnX1DMWAG3EvcQiZFN',
    object: 'invoice',
    account_country: 'US',
    account_name: 'PushSend Ai, LLC',
    account_tax_ids: null,
    amount_due: 49400,
    amount_paid: 49400,
    amount_remaining: 0,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 1,
    attempted: true,
    auto_advance: false,
    automatic_tax: { enabled: false, status: null },
    billing_reason: 'subscription_create',
    charge: 'ch_3OHPb8DnX1DMWAG31Hl4tVya',
    collection_method: 'charge_automatically',
    created: 1701171422,
    currency: 'usd',
    custom_fields: null,
    customer: 'cus_P5amQ9ggLORF9V',
    customer_address: {
      city: 'Poughkeepsie',
      country: 'United States',
      line1: '8776 Pennsylvania',
      line2: 'St.Poughkeepsie, NY',
      postal_code: '12601',
      state: 'NY'
    },
    customer_email: 'ghosty00@gmail.dev',
    customer_name: 'Ghosty',
    customer_phone: null,
    customer_shipping: { address: [Object], name: 'Ghosty', phone: null },
    customer_tax_exempt: 'none',
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: {
      id: 'di_1OHPb8DnX1DMWAG3hjv1Ult7',
      object: 'discount',
      checkout_session: null,
      coupon: [Object],
      customer: 'cus_P5amQ9ggLORF9V',
      end: null,
      invoice: null,
      invoice_item: null,
      promotion_code: null,
      start: 1701171422,
      subscription: 'sub_1OHPb8DnX1DMWAG3OJLJWyRW'
    },
    discounts: [ 'di_1OHPb8DnX1DMWAG3hjv1Ult7' ],
    due_date: null,
    effective_at: 1701171422,
    ending_balance: 0,
    footer: null,
    from_invoice: null,
    hosted_invoice_url: 'https://invoice.stripe.com/i/acct_1O1qA4DnX1DMWAG3/test_YWNjdF8xTzFxQTREblgxRE1XQUczLF9QNWFtSmk4VXFNSUlkZlppalA0aDlDQnB1eWFBVUdZLDkxNzEyMjI00200LlwpfHza?s=ap',
    invoice_pdf: 'https://pay.stripe.com/invoice/acct_1O1qA4DnX1DMWAG3/test_YWNjdF8xTzFxQTREblgxRE1XQUczLF9QNWFtSmk4VXFNSUlkZlppalA0aDlDQnB1eWFBVUdZLDkxNzEyMjI00200LlwpfHza/pdf?s=ap',
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/invoices/in_1OHPb8DnX1DMWAG3EvcQiZFN/lines'
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: '4ABD35F6-0001',
    on_behalf_of: null,
    paid: true,
    paid_out_of_band: false,
    payment_intent: {
      id: 'pi_3OHPb8DnX1DMWAG316krNUn9',
      object: 'payment_intent',
      amount: 49400,
      amount_capturable: 0,
      amount_details: [Object],
      amount_received: 49400,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic',
      client_secret: 'pi_3OHPb8DnX1DMWAG316krNUn9_secret_YNAIYN3yCJi6jyFARSJD8KiqD',
      confirmation_method: 'automatic',
      created: 1701171422,
      currency: 'usd',
      customer: 'cus_P5amQ9ggLORF9V',
      description: 'Subscription creation',
      invoice: 'in_1OHPb8DnX1DMWAG3EvcQiZFN',
      last_payment_error: null,
      latest_charge: 'ch_3OHPb8DnX1DMWAG31Hl4tVya',
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: [Object],
      payment_method_types: [Array],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: 'off_session',
      shipping: null,
      source: 'card_1OHPb6DnX1DMWAG3YGiuHitE',
      statement_descriptor: 'PushSend-AI sub',
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null
    },
    payment_settings: {
      default_mandate: null,
      payment_method_options: null,
      payment_method_types: [Array]
    },
    period_end: 1701171422,
    period_start: 1701171422,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    rendering_options: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: 'paid',
    status_transitions: {
      finalized_at: 1701171422,
      marked_uncollectible_at: null,
      paid_at: 1701171422,
      voided_at: null
    },
    subscription: 'sub_1OHPb8DnX1DMWAG3OJLJWyRW',
    subscription_details: { metadata: {} },
    subtotal: 49900,
    subtotal_excluding_tax: 49900,
    tax: null,
    test_clock: null,
    total: 49400,
    total_discount_amounts: [ [Object] ],
    total_excluding_tax: 49400,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: 1701171422
  },
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: [ 'card' ],
    save_default_payment_method: 'on_subscription'
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1OGzk3DnX1DMWAG3T6LnLJP0',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 49900,
    amount_decimal: '49900',
    billing_scheme: 'per_unit',
    created: 1701072031,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    nickname: null,
    product: 'prod_P5A4oe3GJ52I1W',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed'
  },
  quantity: 1,
  schedule: null,
  start_date: 1701171422,
  status: 'active',
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
  trial_start: null
}

console.log(a.latest_invoice.payment_intent.status);